version: '3.4'

services:
    db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: "password"
      ports:
        - "5432:5432"
      volumes:
        - local_pgdata:/var/lib/postgresql/data
    

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      ports:
        - "5050:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: user@agrconclude.com
        PGADMIN_DEFAULT_PASSWORD: password
      volumes:
        - pgadmin-data:/var/lib/pgadmin
    
volumes:
  local_pgdata:
  pgadmin-data:
      